# Site settings
title: tauCross's Blog
motto: 都别抢！那是我的锅！
email: mstsccls@gmail.com
description: iOS开发者，射箭爱好者，其他乱七八糟的。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.blogtc.com" # the base hostname & protocol for your site
github_username: tauCross

# Build settings
markdown: kramdown
